CREATE TABLE "CONTATO"
(
	EMAIL CHAR(50),
	TELEFONE CHAR(10),
	CELULAR CHAR(11),
	ESTADO CHAR(3),
	CIDADE CHAR(40),
	CEP CHAR(11),
	RUA CHAR(40),
	NUMERO INT,
	CONSTRAINT PK_CONTATO PRIMARY KEY (EMAIL)
);

CREATE TABLE "FUNCIONARIOS"
(
	COD_FUNCIONARIO INT,
	PRIMEIRO_NOME CHAR(15),
	SEGUNDO_NOME CHAR(40),
	DATA_NASC DATE,
	CPF CHAR(10) NOT NULL,
	RG CHAR(10) NOT NULL,
	CTPS CHAR(10) NOT NULL,
	CONTATO CHAR(50) NULL,
	DATA_ADMISSAO DATE NOT NULL,
	SALARIO FLOAT,
	CARGO CHAR(30) NOT NULL,
	CONSTRAINT PK_FUCIONARIOS PRIMARY KEY (COD_FUNCIONARIO, CPF),
	CONSTRAINT FK_CONTATO FOREIGN KEY (CONTATO)
	REFERENCES CONTATO(EMAIL)
);

CREATE TABLE ACESSO(
    	ID_LOGIN INT,
    	EMAIL VARCHAR(50),
   	SENHA VARCHAR(12),
    	ATIVO CHAR(1),
    	PERFIL VARCHAR(15),
	CONSTRAINT PK_ID PRIMARY KEY (ID_LOGIN),
	CONSTRAINT FK_ID FOREIGN KEY (ID_LOGIN) REFERENCES FUNCIONARIOS(COD_FUNCIONARIO),
	CONSTRAINT FK_EMAIL FOREIGN KEY (EMAIL) REFERENCES CONTATO(EMAIL),
);

INSERT INTO "CONTATO" VALUES 
	('adm@violet_games.com', '123', '123', 'SP', 'Mau�', '12345', 'Teste', '1234'),
	('bck@violet_games.com', '123', '123', 'SP', 'Mau�', '12345', 'Teste', '1234');

INSERT INTO "FUNCIONARIOS" VALUES
	('001', 'ADM', null, null, '1234', '12345', '123456', 'adm@violet_games.com', '20190812', null, 'Sistema', 'admin', '12345'),
	('002', 'BCK', null, null, '12345', '1234', '123456', 'bck@violet_games.com', '20190812', null, 'Sistema', 'backup', '12345');

select * from CONTATO;
select * from FUNCIONARIOS;

DROP TABLE FUNCIONARIOS;
DROP TABLE CONTATO;
